before_install:
    - sudo apt-get update -qq
    - sudo apt-get install libpam-dev
    - sudo apt-get install libssl-dev
    - sudo apt-get install libpcap-dev

notifications:
    webhooks:
      urls:
        - https://webhooks.gitter.im/e/99792de66d1b43ebb54d
      on_success: change
      on_failure: always
      on_start: false

language: python

python:
    - "2.6"
    - "2.7"

env:
    - CC=gcc
    - CC=clang

script:
    ./utils/run-tests.sh tests
